name = "Chickenhead"
author = "Hri7566"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "5c3ee1ca1782cd5de45267c68fd61dde4ad7e67a1249b115c43433d180b8dfd1"

[versions]
fabric = "0.15.10"
minecraft = "1.20.4"
