name = "Chickenhead"
author = "Hri7566"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "86e734e0a9a9b010e0a36faeb453e5b35eb1a6cf1334b0c116b3ef8d68472932"

[versions]
fabric = "0.15.10"
minecraft = "1.20.4"
